// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramWishlistBot.Data;

#nullable disable

namespace TelegramWishlistBot.Migrations
{
    [DbContext(typeof(WishlistDbContext))]
    [Migration("20260922061600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramWishlistBot.Models.ItemUrl", b =>
                {
                    b.Property<int>("ItemUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemUrlId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ItemUrlId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemUrls");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishlistItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WishlistItemId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.ItemUrl", b =>
                {
                    b.HasOne("TelegramWishlistBot.Models.WishlistItem", "Item")
                        .WithMany("ItemUrls")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.WishlistItem", b =>
                {
                    b.Navigation("ItemUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
