// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramWishlistBot.Data;

#nullable disable

namespace TelegramWishlistBot.Migrations
{
    [DbContext(typeof(WishlistDbContext))]
    partial class WishlistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramWishlistBot.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("AppUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.ItemUrl", b =>
                {
                    b.Property<int>("ItemUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemUrlId"));

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int>("WishlistItemId")
                        .HasColumnType("integer");

                    b.HasKey("ItemUrlId");

                    b.HasIndex("WishlistItemId");

                    b.ToTable("ItemUrls");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishlistItemId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WishlistItemId");

                    b.HasIndex("AppUserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.ItemUrl", b =>
                {
                    b.HasOne("TelegramWishlistBot.Models.WishlistItem", "Item")
                        .WithMany("ItemUrls")
                        .HasForeignKey("WishlistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.WishlistItem", b =>
                {
                    b.HasOne("TelegramWishlistBot.Models.AppUser", "AppUser")
                        .WithMany("WishlistItems")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.AppUser", b =>
                {
                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("TelegramWishlistBot.Models.WishlistItem", b =>
                {
                    b.Navigation("ItemUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
